### ISSUE TITLE
Please, release a version

### ISSUE THREAD

**Issue by eribertomota** [pixel/hexedit#12]
Hi,

I am the hexedit maintainer in Debian. Can you set releases in GitHub? It is useful to allow Debian to monitor changes in hexedit.

Thanks!

Eriberto

**Comment by prigaux** [comment]
I just did https://github.com/pixel/hexedit/releases/tag/1.3

Ok ?

**Comment by eribertomota** [comment]
Hi!

Thanks! However, hexedit doesn't build now. The attached patch is a way to
fix it and to remove a file created by build process and forgotten by clean;

I uploaded the 1.3 version to Debian now.

Cheers,

Eriberto


2016-11-21 9:55 GMT-02:00 Pascal Rigaux <notifications@github.com>:

**Comment by eribertomota** [comment]
Adding the patch... (the patch sent in message via email was dropped)

[30_fix-FTBFS.patch.txt](https://github.com/pixel/hexedit/files/604505/30_fix-FTBFS.patch.txt)

**Comment by ilovezfs** [comment]
@prigaux ping regarding the patch. The build does seem to be broken without it.

RE: https://github.com/Homebrew/homebrew-core/pull/17779

**Comment by prigaux** [comment]
Sorry for not commenting the patch earlier, but i do not agree about the hexedit.1.in part.

To build, you must:
`./autogen.sh && ./configure && make install`
especially, configure will take care of:
`config.status: creating hexedit.1`

As for "distclean", why not a few other files would also need to be removed (hexedit.1, configure...). Pull request accepted :)

**Comment by ilovezfs** [comment]
@prigaux there is no autogen.sh in the 1.3.0 tarball and the issue seems to be fixed in HEAD, but 1.3.0 fails even after `autoreconf -fiv`.
```
/usr/bin/install -c -m 644 hexedit.1 /usr/local/Cellar/hexedit/1.3/share/man/man1
install: hexedit.1: No such file or directory
make: *** [install] Error 71
```

So maybe tagging a new release would do the trick?

Also Debian is applying two other patches:
```
iMac-TMP:patches joe$ cat 10_fix_Makefile_no_strip.patch 
Description: fix Makefile no strip. (Closes: #437161)
Author: Alexander Schmehl <tolimar@debian.org>
Last-Update: 2008-02-21
Index: hexedit-1.2.13/Makefile.in
===================================================================
--- hexedit-1.2.13.orig/Makefile.in
+++ hexedit-1.2.13/Makefile.in
@@ -42,6 +42,6 @@ distclean: clean
 
 install: $(PRODUCT)
 	$(INSTALL) -d -m 755 $(DESTDIR)$(bindir)
-	$(INSTALL) -s -m 755 $(PRODUCT) $(DESTDIR)$(bindir)
+	$(INSTALL) -m 755 $(PRODUCT) $(DESTDIR)$(bindir)
 	$(INSTALL) -d -m 755 $(DESTDIR)$(mandir)/man1
 	$(INSTALL) -m 644 $(PRODUCT).1 $(DESTDIR)$(mandir)/man1
iMac-TMP:patches joe$ cat 20_fix_manpage_spellings.patch 
Description: fix spelling errors.
Author: Alexander Schmehl <tolimar@debian.org>
Reviewed-by: Joao Eriberto Mota Filho <eriberto@debian.org>
Last-Update: 2016-11-21
Index: hexedit-1.3/hexedit.1.in
===================================================================
--- hexedit-1.3.orig/hexedit.1.in
+++ hexedit-1.3/hexedit.1.in
@@ -113,7 +113,7 @@ o \fIF1\fR, \fIEsc+H\fR \- help (show th
 .br
 o \fICtrl+O\fR, \fIF3\fR \- open another file
 .br
-o \fICtrl+L\fR \- redisplay (refresh) the display (usefull when your terminal screws up).
+o \fICtrl+L\fR \- redisplay (refresh) the display (useful when your terminal screws up).
 .br
 o \fIBackspace\fR, \fICtrl+H\fR \- undo the modifications made on the previous byte.
 .br
@@ -247,7 +247,7 @@ The hexadecimal search could be able to
 Another feature could be to complete padd odd length hexadecimal searches with
 zeros.
 .SH BUGS
-I have an example where the display is completly screwed up. It seems to be a
+I have an example where the display is completely screwed up. It seems to be a
 bug in ncurses (or maybe in xterm and rxvt)?? Don't know if it's me using
 ncurses badly or not... It seems to happen when \fIhexedit\fR leaves only one
 space at the end of the lines... If anyone has a (or the) solution, please tell
```

**Comment by ilovezfs** [comment]
@prigaux Specifically https://github.com/pixel/hexedit/commit/f3e39a5121040658632b1726faf4a803ce85a221 is what fixed it, which came just after 1.3

**Comment by ilovezfs** [comment]
@prigaux here are PRs for Debian's patches:
https://github.com/pixel/hexedit/pull/20
https://github.com/pixel/hexedit/pull/21

**Comment by prigaux** [comment]
Oops, thanks for all this.
I released 1.4
Then I saw your pull requests which I accepted and released 1.4.1

**Comment by ilovezfs** [comment]
@prigaux Sweet! You're awesome :)

**Comment by eribertomota** [comment]
Thnaks!

2017-09-07 11:43 GMT-03:00 Pascal Rigaux <notifications@github.com>:
