### ISSUE TITLE
Version wrong (1.4.1)

### ISSUE THREAD

**Issue by eribertomota** [pixel/hexedit#23]
Dear upstream,

In configure.ac file from hexedit 1.4.1 I can see:

define(TheVERSION, 1.4)

This issue is not valid for next release. So, I can't make a push request. I suggest a check list to release, as I made in Axel[1].

[1] https://github.com/axel-download-accelerator/axel/blob/master/doc/UPDATE-CHECK

Regards,

Eriberto

**Comment by prigaux** [comment]
I released a clean 1.4.2

**Comment by eribertomota** [comment]
2017-09-15 4:04 GMT-03:00 Pascal Rigaux <notifications@github.com>:

> I released a clean 1.4.2
>


Thanks!
