### ISSUE TITLE
Offset displayed in the left column wraps past 4GB, not enough digits

### ISSUE THREAD

**Issue by eribertomota** [pixel/hexedit#26]
This bug is from Debian[1].

> Past 4GB the offset displayed in the left column wraps. There are just not enough digits, the displayed data 
> itself seems to be ok.

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=304105

Thanks!

**Comment by prigaux** [comment]
Well, for me it's not a bug, it's a "functionality" to display the rounded down offset...

**Comment by eribertomota** [comment]
2017-09-15 3:59 GMT-03:00 Pascal Rigaux <notifications@github.com>:

> Well, for me it's not a bug, it's a "functionality" to display the rounded
> down offset...
>
>

Your program is useful for forensics investigations and other activities.
Can you use more bytes to show the offset?

Thanks

**Comment by prigaux** [comment]
the full offset is displayed at the bottom of the term. Not enough?

**Comment by eribertomota** [comment]
2017-09-15 11:55 GMT-03:00 Pascal Rigaux <notifications@github.com>:

> the full offset is displayed at the bottom of the term. Not enough?
>
>
>
I will check it. Thanks.

**Comment by eribertomota** [comment]
Hi! I think that it is fine.

Thanks for your attention.

Regards,

Eriberto
