### ISSUE TITLE
"long long int" warnings

### ISSUE THREAD

**Issue by stevenhoneyman** [pixel/hexedit#3]
Compiling with "-Wall -Wextra" as I usually do, I get two warnings that seem to show a type mismatch:

```
display.c: In function ‘get_number’:
display.c:274:5: warning: format ‘%llx’ expects argument of type ‘long long unsigned int *’, but argument 3 has type ‘off_t *’ [-Wformat=]
     err = sscanf(tmp + strlen("0x"), "%llx", i);
     ^
display.c:276:5: warning: format ‘%lld’ expects argument of type ‘long long int *’, but argument 3 has type ‘off_t *’ [-Wformat=]
     err = sscanf(tmp, "%lld", i);
     ^
```

It seems to have been fixed in this commit on a seperate fork:
https://github.com/rofl0r/hexedit0r/commit/5adb43976e50442547b69cbc55acf1c1aaabe2a7.patch

**Comment by eribertomota** [comment]
The quoted patch isn't updated. I will submit a push request to fix.

**Comment by prigaux** [comment]
I'd say this issue is fixed by https://github.com/pixel/hexedit/pull/36
