### ISSUE TITLE
Malformed address in first line

### ISSUE THREAD

**Issue by eribertomota** [pixel/hexedit#31]
Hi,

In Debian Sid, the hexedit is truncanting the address in first line. See below:

```
0   46 6F 72 6D  61 74 3A 20  68 74 74 70  73 3A 2F 2F  77 77 77 2E  64 65 62 69  Format: https://www.debi
00000018   61 6E 2E 6F  72 67 2F 64  6F 63 2F 70  61 63 6B 61  67 69 6E 67  2D 6D 61 6E  an.org/doc/packaging-man
00000030   75 61 6C 73  2F 63 6F 70  79 72 69 67  68 74 2D 66  6F 72 6D 61  74 2F 31 2E  uals/copyright-format/1.
00000048   30 2F 0A 55  70 73 74 72  65 61 6D 2D  4E 61 6D 65  3A 20 68 65  78 65 64 69  0/.Upstream-Name: hexedi
00000060   74 0A 53 6F  75 72 63 65  3A 20 68 74  74 70 3A 2F  2F 72 69 67  61 75 78 2E  t.Source: http://rigaux.
00000078   6F 72 67 2F  68 65 78 65  64 69 74 2E  68 74 6D 6C  20 6F 72 0A  20 20 20 20  org/hexedit.html or.
00000090   20 20 20 20  68 74 74 70  73 3A 2F 2F  67 69 74 68  75 62 2E 63  6F 6D 2F 70      https://github.com/p
000000A8   69 78 65 6C  2F 68 65 78  65 64 69 74  0A 0A 46 69  6C 65 73 3A  20 2A 0A 43  ixel/hexedit..Files: *.C
```

Thanks,

Eriberto

**Comment by prigaux** [comment]
Works for me with hexedit 1.4.2-3

**Comment by eribertomota** [comment]
Em seg, 1 de out de 2018 às 04:31, Pascal Rigaux <notifications@github.com>
escreveu:

> Works for me with hexedit 1.4.2-3
>
>
>
Thanks for your reply. I installed a VM running Buster and I got the same
results.

**Comment by eribertomota** [comment]
I think I found the problem. hexedit fails over some terminal types. In my
system it fails inside a jail made with debootstrap command and over ssh
operations.

# debootstrap sid /test http://ftp.debian.org/debian
# chroot  /test
# apt-get install hexedit
# date > test
# hexedit test

Thanks in advanced.

Cheers,

Eriberto



Em qua, 3 de out de 2018 às 06:27, Pascal Rigaux <notifications@github.com>
escreveu:

**Comment by eribertomota** [comment]
Taking advantage of these messages, can you implement a -v option to show version? I intent to use it for CI test in Debian (a trivial test only, to see automatically if the command runs after each build  in Debian).

Thanks.

**Comment by prigaux** [comment]
Works for me with xterm which sets TERM=xterm.

hexedit refuses to start with rxvt-unicode which sets TERM=rxvt-256color
with TERM=rxvt it works.

**Comment by prigaux** [comment]
For CI test, you could do `hexedit -h 2>&1 | grep -q '^usage'` ?

**Comment by eribertomota** [comment]
> Works for me with xterm which sets TERM=xterm.
> 
> hexedit refuses to start with rxvt-unicode which sets TERM=rxvt-256color
> with TERM=rxvt it works.

Hum... Works for me with TERM=linux too. Isn't it a bug in hexedit? Note that a ssh connection will not set a special term and hexedit will show the first line wrong. Other programs work fine.

> For CI test, you could do `hexedit -h 2>&1 | grep -q '^usage'` ?

Seems correct. I will try it.

Thanks!

Eriberto

**Comment by mokraemer** [comment]
I have the same problem, first line is broken!
Setting TERM does not change anything.

**Comment by mokraemer** [comment]
what do you need for diagnosis?
I can confirm, setting
TERM=linux hexedit SOURCES/hexedit-1.4.2.tar.gz
works. With TERM=xterm it does not.

**Comment by prigaux** [comment]
Which terminal are you using?
No issue with
* ubuntu 18.04 with xterm (which has TERM=xterm) and gnome-terminal.
* debian buster with xterm and rxvt-unicode (with TERM=rxvt-256color which requires package ncurses-term)
Maybe you can add the output of `tput cols` in case the bug is terminal size dependent.

**Comment by mokraemer** [comment]
I'm using Mageia 6 with LXDE Desktop
- plain old xterm works with (default) terminal set to xterm
- lxterminal does not work with (default) terminal set to xterm
- gnome-terminal does not work with (default) terminal set to xterm

nope, the output does not depend on the size of the terminal. Just the first row, the hex adress 0 is just printed as 0 not as "00000000". I'm confused this depends on the terminal set.

**Comment by malaterre** [comment]
I can reproduce it over here using Ubuntu 19.04. My ssh session reports:

```
$ echo $TERM
xterm-256color
```

And editing the output of date gives ($ date > d):

`$ hexedit d`

```
0   57 65 64 20  41 70 72 20  20 31 20 30  38 3A 31 32  3A 35 31 20  43 45 53 54  20 32 30 32  30 0A                                                      Wed Apr  1 08:12:51 CEST 2020.
0000002C
```

I would expect something like:

```
00000000   57 65 64 20  41 70 72 20  20 31 20 30  38 3A 31 34  3A 35 34 20  43 45 53 54  20 32 30 32  30 0A                                               Wed Apr  1 08:14:54 CEST 2020.
0000002C
```

**Comment by malaterre** [comment]
Here is the output of:

$ TERM=xterm-256color hexedit d

gives:

```
0   57 65 64 20  41 70 72 20  20 31 20 30  38 3A 31 32  3A 35 31 20  43 45 53 54  20 32 30 32  30 0A                                                      Wed Apr  1 08:12:51 CEST 2020.
0000002C
```

while

`$ TERM=xterm-color hexedit d
`
gives:

```
00000000   57 65 64 20  41 70 72 20  20 31 20 30  38 3A 31 32  3A 35 31 20  43 45 53 54  20 32 30 32  30 0A                                               Wed Apr  1 08:12:51 CEST 2020.
0000002C

```

**Comment by malaterre** [comment]
Just for reference comparing the output of teseq of script(s) output may give a hint:

```
@@ -41,25 +45,36 @@
 : Esc [ H
 & CUP: CURSOR POSITION
 " Move the cursor to line 1, column 1.
-: Esc [ J
+: Esc [ 2 J
 & ED: ERASE IN PAGE
-" Clear from the cursor to the end of the screen.
-|00000000   57 65 64 20  41 70 72 20  20 31 20 30  38 3A 35 39  3A 33 35 20 |-
--| 43 45 53 54  20 32 30 32  30 0A|
+" Clear the screen.
+: Esc [ ? 1 h
+& SM: SET MODE (private params)
+" (DEC) Cursor key mode.
+: Esc =
+& DECKPAM: KEYPAD APPLICATION MODE
+|0|
+: Esc [ 7 b
+& REP: REPEAT
+|   57 65 64 20  41 70 72 20  20 31 20 30  38 3A 35 39  3A 33 35 20  43 45 5|-
+-|3 54  20 32 30 32  30 0A|

```

**Comment by eribertomota** [comment]
This issue and others are open since some years ago. Is time for external help? Maybe a call for help in README.md file can help this nice project.

**Comment by prigaux** [comment]
I finally reproduced this issue through ssh on ubuntu 18.

I was able to reproduce using a minimal prog:
```c
#include <curses.h>
int main() {
  initscr(); noecho(); printw("0000000"); getch();
}
```

IMO this need to be fixed elsewhere!

**Comment by mokraemer** [comment]
strangely I'm not able to reproduce this anymore (hexedit-1.4.2), maybe because of my desktop switch from lxde to lxqt...
My TERM is xterm-256color and the output of hexedit is "000000" again...

**Comment by malaterre** [comment]
@mokraemer Can you try again but do `ssh localhost` first ?

**Comment by mokraemer** [comment]
it works with ssh too

**Comment by malaterre** [comment]
@pixel This is driving my nuts. When I compile it as static:

    $ gcc -o t t.c /lib/x86_64-linux-gnu/libncurses.a /lib/x86_64-linux-gnu/libtinfo.a

I can reproduce it on my Ubuntu 19.04 system, if I `scp` the exec onto my local fedora system I can no longer reproduce it.

**Comment by malaterre** [comment]
@pixel I found the issue. When comparing the output of teseq I noticed this:

```
& ED: ERASE IN PAGE
" Clear the screen.
|0|
: Esc [ 6 b
& REP: REPEAT
: Esc [ 46 ; 1 H
& CUP: CURSOR POSITION
```

while in the original one I only see:

```
& ED: ERASE IN PAGE
" Clear the screen.
|0000000|
: Esc [ 46 ; 1 H
& CUP: CURSOR POSITION

```

Doing a goodl search on 'REPEAT' eventually lead to:

* https://unix.stackexchange.com/questions/394787/linux-terminal-skipping-some-repeating-whitespace-characters

**Comment by prigaux** [comment]
Great.

Conclusion: some "TERM" from recent terminfo breaks on old terminal applications.

**Comment by malaterre** [comment]
just for later reference. Bug has been fixed in all Debian system:

* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933053

But not on Ubuntu, so a user has to do:

`$ infocmp xterm-256color | sed -e 's/rep=[^,]*, //' | tic -`

Now you should have 

```
$ infocmp -x xterm-256color | head -n1
#	Reconstructed via infocmp from file: /home/malat/.terminfo/x/xterm-256color
```
