### ISSUE TITLE
cut a release

### ISSUE THREAD

**Issue by furlongm** [pixel/hexedit#43]
Hi,

The last "official" release on rigaux.net is 1.2.13 and that is the version that most linux distributions are still using today.

Would it be possible to cut a release with 1.4.2 or whatever the current latest release is? Github releases will create tarball artifacts automatically, so making a release is just a couple of clicks away.

Thanks!

**Comment by prigaux** [comment]
* 1.5 released and tagged
* http://rigaux.org/hexedit.html has been updated

**Comment by furlongm** [comment]
Great! Thank you!

One patch that most distros have applied is available here: http://www.volkerschatz.com/unix/patches/hexedit-search2a.diff.gz

Might be worthwhile rolling that in, but just noticed it because it no longer cleanly applies.

**Comment by furlongm** [comment]
Also, the tarball at http://riguax.org/hexedit-1.5.src.tgz seems to have `hexedit.1` instead of `hexedit.1.in`, and configure fails.

The tarball on github seems to be fine.
