### ISSUE TITLE
Long file support

### ISSUE THREAD

**Issue by rsaxvc** [pixel/hexedit#68]
Once the cursor offset exceeds 0x7fffffff, the address column has some integer overflow issues, and the cursor misaligns. Similar issues and scrolling rolloff beyond 0xffffffff.

I've started hacking on a patch for these.

**Comment by maneatingcow** [comment]
I've just run into this where e.g. 0x17A138000 displays as 0x7A138000. A fix would be much appreciated!

**Comment by rsaxvc** [comment]
Realizing it has been 3 months, I may not get back to it for a while.
