### ISSUE TITLE
config.h missing / build impossible

### ISSUE THREAD

**Issue by bradenbest** [pixel/hexedit#7]
Building with systems like Autotools is either impossible or exceedingly frustrating for me. I prefer to use a makefile directly or compile manually.

When I try to compile, it tells me that `config.h` is missing. I take it that it's generated by the build system. I tried using the build system (`autoconf configure.in`) and **it** failed because `config.h.in` is missing.

What gives? Is there a template for this file? At this point, I just want to copy a template, adjust it manually, and compile the whole thing myself. Autotools is just getting in the way. If I can't compile something manually, then there is a serious problem with the design of the project. You shouldn't rely on a build system. That's supposed to be there to _help_ automate things; not to be your crutch. And Autotools, in particular, is impossible to work with, and for something that is supposed to make projects portable, it sure as hell doesn't want to build on Linux, the most ubiquitous `*NIX` system in the world.

Take a page from Suckless and include a pre-written `config.def.h` by default.

**Comment by prigaux** [comment]
To build:

autoheader && autoconf && ./configure && make

By the way, most linuxes have a pre-built hexedit package (debian, ubuntu, fedora...)

**Comment by eribertomota** [comment]
Or...

autoreconf -fi && ./configure && make

**Comment by prigaux** [comment]
You can also use the now bundled autogen.sh
